/**
 * Thrown in case next is called twice in same handler.
 * @extends {external:Error}
 * @alias module:errors.NextCalledBefore
 */
class NextCalledBefore extends Error {
  /**
   * Create a NextCalledBefore.
   */
  constructor (message) {
    super(message || 'next() has been called before')
    this.name = this.constructor.name
    Error.captureStackTrace(this, this.constructor)
    this.statusCode = 500
  }
}

module.exports = NextCalledBefore
